language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
  - "pypy"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install mock; fi
script: python -m unittest tests.test_gelfHandler